### ISSUE TITLE
日常之css技巧

### ISSUE THREAD

**Issue by Jackson-p** [Jackson-p/Jackson-p.github.io#40]
#### css 实现字体颜色渐变

https://blog.csdn.net/FE_dev/article/details/78450844
```css
background: linear-gradient(to right, #FEE779 100%, #F9C93C 100%);
background-clip: text;
color: transparent;
```

#### css 遮挡modal效果

```css
    .cover{
        background: rgba(0,0,0,0.70);
        position: fixed;
        left: 0;
        top: 0;
        width: 100%;
        height: 100vh;
        display: none;
        z-index: 2;
    }
```
#### css 实现图片自填充

```css
    img{
        width: 100%;
        height: 100%;
        object-fit: cover;
    }
```

#### css防止点击阴影出现

> -webkit-tap-highlight-color: rgba(0, 0, 0, 0);

#### css 文字渐变效果

```css
background: linear-gradient(to right, #FEE779 100%, #F9C93C 100%);
background-clip: text;
color: transparent;
```
